version: "2"

services:
  controller:
    image: aabadie/ipyparallel:latest
    ports:
     - "8889:8889"
     - "8888:8888"
    command: run controller
    networks:
      - ipyparallel
    container_name: controller

  engine:
    image: aabadie/ipyparallel:latest
    command: engines
    networks:
      - ipyparallel
    links:
      - controller

  notebook:
    image: aabadie/ipyparallel:latest
    command: notebook
    networks:
      - ipyparallel
    links:
      - controller

  console:
    image: aabadie/ipyparallel:latest
    command: console
    networks:
      - ipyparallel
    links:
      - controller

networks:
  ipyparallel:
    # Enable multi-host communication
    driver: overlay
